Resolve error TS5101: Option 'baseUrl' is deprecated
 error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption 'ignoreDeprecations: 6.0' to silence this error. Visit https://aka.ms/ts6 for migration information.